### ISSUE TITLE
README points to wrong repo

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio-livesdr#17]
Is this repo is somehow linked to your personal ubuntu-remaster? The README seems to indicate that. I would have submitted PR changing that, but wasn't sure if that's what you want to do.

**Comment by jmcorgan** [comment]
The master (and xenial) branches are on jmcorgan repo, as that is the base system for doing live remastering for any type of system, and the repo is actually ubuntu-remaster.git.

The GNU Radio livesdr (and livesdr-xenial) branches are a superset of master, and live in the gnuradio github repo, as gnuradio-livesdr.git.

So, the proper thing to do is to PR a change to the README on the livesdr branch, and I'd merge that up to livesdr-xenial branch.

**Comment by jmcorgan** [comment]
The repo on GNU Radio github, by the way, is a github fork of the main repo (ubuntu-remaster).

**Comment by jmcorgan** [comment]
Fixed in #19
