### ISSUE TITLE
kconfig-ncurses PPA does not play well with wily (Ubuntu 15.10)

### ISSUE THREAD

**Issue by mbr0wn** [gnuradio/gnuradio-livesdr#9]
```
$ make deps
[...]
W: Failed to fetch http://ppa.launchpad.net/george-hopkins/kconfig-frontends/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/george-hopkins/kconfig-frontends/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found
```

**Comment by jmcorgan** [comment]
Yeah, I don't think he's packaged it for wily.

**Comment by jmcorgan** [comment]
In general, I've stuck with 14.04 for doing the build, but making a target using 15.10 should work.

**Comment by mbr0wn** [comment]
I've pinged him if he can update.

**Comment by jmcorgan** [comment]
Also beware that if you build using 15.10 you'll need to merge in the 'add-overlay-workdir' branch, due to a change in the kernel used in 15.10.  I'm working on automating this.

**Comment by jmcorgan** [comment]
This has been fixed in the livesdr-xenial branch.
